# Habilita o display e a tela de status
CONFIG_ZMK_DISPLAY=y
CONFIG_ZMK_DISPLAY_STATUS_SCREEN=y

# Ajusta as posições X/Y dos elementos para 128x32
CONFIG_ZMK_DISPLAY_STATUS_SCREEN_IMAGE_POSITION_X=0
CONFIG_ZMK_DISPLAY_STATUS_SCREEN_IMAGE_POSITION_Y=0

CONFIG_ZMK_DISPLAY_STATUS_SCREEN_LAYER_STATE_POSITION_X=0
CONFIG_ZMK_DISPLAY_STATUS_SCREEN_LAYER_STATE_POSITION_Y=0

CONFIG_ZMK_DISPLAY_STATUS_SCREEN_BATTERY_POSITION_X=90
CONFIG_ZMK_DISPLAY_STATUS_SCREEN_BATTERY_POSITION_Y=0

CONFIG_ZMK_DISPLAY_STATUS_SCREEN_OUTPUT_SELECTION_POSITION_X=0
CONFIG_ZMK_DISPLAY_STATUS_SCREEN_OUTPUT_SELECTION_POSITION_Y=16

CONFIG_ZMK_DISPLAY_STATUS_SCREEN_USB_CONNECTION_POSITION_X=64
CONFIG_ZMK_DISPLAY_STATUS_SCREEN_USB_CONNECTION_POSITION_Y=16

# (Opcional) Desativa WPM pra economizar espaço
# CONFIG_ZMK_DISPLAY_STATUS_SCREEN_WPM=n
