# sofle_left.conf
#
# O sofle.conf global já habilita CONFIG_ZMK_DISPLAY=y e CONFIG_I2C=y.
# Aqui apenas garantimos o driver do SSD1306 (OLED 128x32).
# Nenhuma configuração de trackpad necessária neste lado.
CONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
CONFIG_INPUT=y
CONFIG_ZMK_MOUSE=y
CONFIG_ZMK_POINTING=y
CONFIG_INPUT_AZOTEQ_IQS5XX=y

CONFIG_ZMK_DISPLAY=y
CONFIG_SSD1306=y


