# sofle_left.conf
#
# O sofle.conf global já habilita CONFIG_ZMK_DISPLAY=y e CONFIG_I2C=y.
# Aqui apenas garantimos o driver do SSD1306 (OLED 128x32).
# Nenhuma configuração de trackpad necessária neste lado.
CONFIG_ZMK_SPLIT_ROLE_CENTRAL=y
CONFIG_INPUT=y
CONFIG_ZMK_MOUSE=y
CONFIG_ZMK_POINTING=y
CONFIG_INPUT_AZOTEQ_IQS5XX=y

CONFIG_ZMK_DISPLAY=y
CONFIG_SSD1306=y



# Flags exclusivas do lado Esquerdo (Mestre)
CONFIG_ZMK_DISPLAY_STATUS_SCREEN_CUSTOM=y
CONFIG_NICE_OLED_WIDGET_ANIMATION_PERIPHERAL_CAT=y

# Aumenta a memória para a animação
CONFIG_LV_Z_MEM_POOL_SIZE=16384  

# Garante que o display não atrase o processamento de teclas
CONFIG_ZMK_DISPLAY_WORK_QUEUE_DEDICATED=y

# Opcional: Se o gato estiver muito "rápido" e roubando CPU, 
# você pode limitar o FPS dele (ajuda muito no delay da digitação)
# Fila dedicada para o display não engasgar as teclas (ESSENCIAL pro delay)